### ISSUE TITLE
In cv_container configlet_attached is updated even if not used

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#108]
Issue Type
------
 - Bug Report

Module Name
------

`arista.cvp` collection and Python libraries version

```
arista.cvp==1.0.2
cv-container
```

Summary
------

Steps to reproduce
------

__group_vars__

```yaml
---
CVP_CONTAINERS:
  TEAM01:
    parent_container: Tenant
  TEAM01_DC:
    parent_container: TEAM01
  TEAM01_LEAFS:
    parent_container: TEAM01_DC
```

__Playbook__

```yaml
---
- name: lab04 - cv_container lab
  hosts: CloudVision
  connection: local
  gather_facts: no

  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: CVP_FACTS

    - name: "Configure containers on {{inventory_hostname}}"
      arista.cvp.cv_container:
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        topology: "{{CVP_CONTAINERS}}"
        save_topology: true
      register: CVP_CONTAINERS_RESULT

    - name: 'Display cv_configlet result'
      debug:
        msg: '{{CVP_CONTAINERS_RESULT}}'
```

Expected results

```json
"data": {
            "attached_configlet": {
                "configlet_attached": 0, 
                "list": [], 
                "taskIds": []
            }, 
            "changed": true, 
            "creation_result": {
                "containers_created": "2"
            }, 
            "moved_result": {
                "devices_moved": 0, 
                "list": [], 
                "taskIds": []
            }, 
            "taskIds": [], 
            "tasks": []
        }, 
        "failed": false
    }
```

Actual results
------

```json
"data": {
            "attached_configlet": {
                "configlet_attached": 3, 
                "list": [
                    [], 
                    [], 
                    []
                ], 
                "taskIds": []
            }, 
            "changed": true, 
            "creation_result": {
                "containers_created": "2"
            }, 
            "moved_result": {
                "devices_moved": 0, 
                "list": [], 
                "taskIds": []
            }, 
            "taskIds": [], 
            "tasks": []
        }, 
        "failed": false
    }
```

**Comment by titom73** [comment]
Code updated and result is now coherent:

```
ok: [CloudVision] => 
  msg:
    changed: false
    cv_container:
      attached_configlet:
        configlet_attached: 0
        list: []
        taskIds: []
      changed: true
```
