### ISSUE TITLE
 cannot execute tasks with cv_task module 

### ISSUE THREAD

**Issue by roman-cvp** [aristanetworks/ansible-cvp#109]
Might be related to https://github.com/aristanetworks/ansible-cvp/issues/79

Issue Type
------

 - Bug Report

Module Name
------
cv_task

`arista.cvp` collection and Python libraries version

```
ansible 2.9.2
  config file = /scripts/test_unitaires_aristacvp/ansible.cfg
  configured module search path = [u'/scripts/plugins/modules', u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jan 31 2019, 00:15:21) [GCC 6.3.0]

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
ansible==2.9.2
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
enum34==1.1.6
idna==2.8
ipaddress==1.0.23
Jinja2==2.10.3
MarkupSafe==1.1.1
pycparser==2.19
PyYAML==5.2
requests==2.22.0
six==1.13.0
treelib==1.5.5
urllib3==1.25.7


```

OS / Environment
------

CloudVision version
2018.2.5
UI version1.11.0

Summary
------

The tasks are not executed. The pending tasks are been identified but the module cv_task returns error

Steps to reproduce
------

CVP before :
 
![image](https://user-images.githubusercontent.com/59204786/71418313-29ece000-266a-11ea-898a-c6094e61797b.png)

Playbook
```
---
- name: Playbook to validate and demonstrate cv_container module.
  hosts: cvp
  connection: local
  gather_facts: no
  collections:
    - arista.cvp
  
  vars:
    containers_provision:
      IPFabric:
        parent_container: Tenant
        devices:
        - eos-1
        - eos-2
        - eos-3
        - eos-4

  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: cvp_facts
      tags:
        - always

    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container:
        topology: '{{containers_provision}}'
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        save_topology: true
        mode: override
 #######################################################################""   
    - name: Display tasks
      tags:
        - provision
      debug:
        msg: "{{tasks}}" 

    - name: Display cvp_facts.ansible_facts.tasks
      tags:
        - provision
      debug:
        msg: "{{tasks}}"  

    - name: 'Execute all pending tasks and wait for completion for 60 seconds'
      arista.cvp.cv_task:
        tasks: "{{ tasks }}"
        wait: 60

```
CVP after execution the playbook
![image](https://user-images.githubusercontent.com/59204786/71418387-85b76900-266a-11ea-819b-050227c5ea93.png)

Expected results
the tasks shown in cvp should have been executed

Actual results
------
Tasks created but in pending

**Comment by titom73** [comment]
Hello @roman-cvp 

As per your playbook, I can see you created a topology using `arista.cvp.cv_container`

```yaml
- name: "Build Container topology on {{inventory_hostname}}"
  arista.cvp.cv_container:
    topology: '{{containers_provision}}'
    cvp_facts: '{{cvp_facts.ansible_facts}}'
    save_topology: true
    mode: override
```

It seems you did not save result of this task and you call an undefined variable:

```yaml
- name: 'Execute all pending tasks and wait for completion for 60 seconds'
  arista.cvp.cv_task:
    tasks: "{{ tasks }}"
    wait: 60
```

Could you try with a playbook like this one:

```yaml
- name: "Build Container topology on {{inventory_hostname}}"
  arista.cvp.cv_container:
    topology: '{{containers_provision}}'
    cvp_facts: '{{cvp_facts.ansible_facts}}'
    save_topology: true
    mode: override
  register: cvp_container_result

- name: 'Execute all pending tasks and wait for completion for 60 seconds'
  arista.cvp.cv_task:
    tasks: "{{ cvp_container_result.data.tasks }}"
    wait: 60
```

You can also share `cvp_container_result` content from a debug task.

Regards,

**Comment by AJNOURI** [comment]
Hi @titom73,
Thanks for your reply. We are with @roman-cvp  on this :)
- Should we conclude that we need to register the result of each module to execute the related tasks?
Something like below:

**cv_container**
```
  arista.cvp.cv_container:
    topology: '{{containers_provision}}'
    cvp_facts: '{{cvp_facts.ansible_facts}}'
    save_topology: true
    mode: override
  register: cvp_container_result
```

**cvp_configlet_result**
```
- name: 'Create configlets on CVP {{inventory_hostname}}.'
    arista.cvp.cv_configlet:
      cvp_facts: "{{cvp_facts.ansible_facts}}"
      configlets: "{{configlet_list}}"
      configlet_filter: ["AVD"]
  register: cvp_configlet_result
```
**cv_device**
```
  - name: "Configure devices on {{inventory_hostname}}"
    arista.cvp.cv_device:
      devices: "{{devices_inventory}}"
      cvp_facts: '{{cvp_facts.ansible_facts}}'
      device_filter: ['veos']
      state: present
  register: cvp_device_result
```

---------
- Is there a difference between module references like "arista.cvp.cv_device" and "cv_device" ? Both works which one should we stick to?

---------

By the way, here is the error we mentioned in the Summary:
[out.playbook.container.4.txt](https://github.com/aristanetworks/ansible-cvp/files/4002862/out.playbook.container.4.txt)

**Comment by titom73** [comment]
> Should we conclude that we need to register the result of each module to execute the related tasks?
Something like below:

Yes you shall provide a list of tasks to execute to that module. To do that, you have 2 options:
- Get output of another arista.cvp modules to run not all pending tasks but only tasks you generated before
- Send tasks collected in `arista.cvp.cv_facts` to run all pending tasks regardless if they are yours or not.

> Is there a difference between module references like "arista.cvp.cv_device" and "cv_device" ? Both works which one should we stick to?

`arista.cvp.xxx` is new syntax introduce in ansible 2.9 with collection. So both approach are OK as long as collection is installed in your default collections paths and you do not have duplicate names. 

You can find more information about Ansible collection on this [page](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html)

Going back to your issue, error message might be the result of a incorrect format in your tasks structure. Using empty variable as an input might be the root cause. Could you run the test describe in previous reply and share result ?

**Comment by AJNOURI** [comment]
In the previous reply I posted the file:
[out.playbook.container.4.txt](https://github.com/aristanetworks/ansible-cvp/files/4003064/out.playbook.container.4.txt)

**Comment by titom73** [comment]
Seems your file is an old one from December 24th where you still refers to `{{tasks}}` and not output of `arista.cvp.cv_container`

We can see starting line [935](https://gist.github.com/titom73/57a19500fc0e47e573b40aa245296342#file-log-txt-L935) a list of tasks ready to be consumed by `arista.cvp.cv_tasks` module.

Please run this updated playbook and share result in a gist:

```yaml
---
- name: Playbook to validate and demonstrate cv_container module.
  hosts: cvp
  connection: local
  gather_facts: no
  collections:
    - arista.cvp
  
  vars:
    containers_provision:
      IPFabric:
        parent_container: Tenant
        devices:
        - eos-1
        - eos-2
        - eos-3
        - eos-4

  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: cvp_facts
      tags:
        - always

    - name: "Build Container topology on {{inventory_hostname}}"
      arista.cvp.cv_container:
        topology: '{{containers_provision}}'
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        save_topology: true
        mode: override
      register: CVP_CONTAINERS_RESULT
 #######################################################################""   
    - name: Display tasks
      tags:
        - provision
      debug:
        msg: "{{CVP_CONTAINERS_RESULT.data.tasks}}" 

    - name: Display cvp_facts.ansible_facts.tasks
      tags:
        - provision
      debug:
        msg: "{{CVP_CONTAINERS_RESULT.data.tasks}}"  

    - name: 'Execute all pending tasks and wait for completion for 60 seconds'
      arista.cvp.cv_task:
        tasks: "{{ CVP_CONTAINERS_RESULT.data.tasks }}"
        wait: 60
```
