### ISSUE TITLE
Allow cv_device to add configlet without listing all configlets

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#117]
__Use case:__

When devices are all deployed with their configilet, it might be useful to add a new configlet to device using `cv_device` module.

Current module implementation requires to list all configlet and add new configlet to the list. This approach means user has to maintain list of configlets per device and run a workflow close to the rollout targeting a larger scope than just _1 device + 1 configlet_

__Change behaviour:__

To allow user to target only one device with one configlet, it can be useful to add an option related to `configlets` in `cv_device` to support addition or deletion of a set of configlets.

Current implementation use the following syntax:

```yaml
vars:
  devices_inventory:
    veos01:
    name: veos01
    configlets:
        - cv_device_test01
        - SYS_TelemetryBuilderV2_172.23.0.2_1
        - veos01-basic-configuration
        - SYS_TelemetryBuilderV2
    parentContainerName: DC1_VEOS
tasks:
    - name: "Configure devices on {{inventory_hostname}}"
      cv_device:
        devices: "{{devices_inventory}}"
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        device_filter: ['veos']
      register: cvp_device
```

To support such change, 2 options could be implemented and both are already present in other modules

- __Use a configlet filter:__

With this approach, configlet filter allows user to target only configlets with a specific string. So as for `cv_container` it is easy to add only one configlet with following example:

```yaml
vars:
  devices_inventory:
    veos01:
    name: veos01
    configlets:
        - veos01-basic-configuration
    parentContainerName: DC1_VEOS
tasks:
    - name: "Configure devices on {{inventory_hostname}}"
      cv_device:
        devices: "{{devices_inventory}}"
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        device_filter: ['veos']
        configlet_filter: ['veos01-basic-configuration']
      register: cvp_device
```

But in case we want to remove it from this device, it is required to fallback to original definition with all configlets.

This approach is similar to filters implemented in `cv_configlet`

- __Use a definition of `mode`__

With implemnentation of a `mode` keyword, we can define 3 different behaviours:
    - override (default): Completely intend based approach and will apply the full list of configlet to device and remove unlisted configlets.
    - merge: Only add new configlets to existing list.
    - delete: Delete list of configlets from device.

```yaml
vars:
  devices_inventory:
    veos01:
    name: veos01
    configlets:
        - veos01-basic-configuration
    parentContainerName: DC1_VEOS
tasks:
    - name: "Configure devices on {{inventory_hostname}}"
      cv_device:
        devices: "{{devices_inventory}}"
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        device_filter: ['veos']
        configlet_mode: merge
      register: cvp_device
```

This approach is similar to `cv_container` with [its `mode` option](https://github.com/aristanetworks/ansible-cvp/wiki/Modules-Documentation#manage-containers-for-network-provisioning)
