### ISSUE TITLE
cv_configlet - Creation of configlet on container raises error

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#13]
When creating a configlet on CVP, ansible raises an error even if configlet is correctly rendered and created on server:

__Task:__

```yaml
    - name: Create a configlet on CVP.
      tags: 
        - configlet
        - provision
      cv_configlet:
        host: '{{ansible_host}}'
        username: '{{cvp_username}}'
        password: '{{cvp_password}}'
        protocol: https
        container: "vLeaves"
        parent: "Ansible_Fabric"
        configletName: "ansible-fabric-vlans"
        template: "{{configlet_template}}"
        data: "{{configlet_data}}"
        action: add
```

__Error message:__

Following line [`cv_configlet.py`/L297](https://github.com/aristanetworks/ansible-cvp/blob/40025842dda9d1444c118972b232ce4c4a6b218b/library/cv_configlet.py#L297) raise an error:

> ansible_cv_configlet_payload_IxU9kQ/__main__.py\", line 297, in
> process_configlet\nUnboundLocalError: local variable 'device_data'
> referenced before assignment

__Ansible version: 2.8.3__

```shell
ansible 2.8.3
  config file = /Users/tgrimonet/Projects/ansible-devel/github/titom73/ansible-cvp-old-private/tests/ansible.cfg
  configured module search path = [u'/Users/tgrimonet/Projects/ansible-devel/github/titom73/ansible-cvp-old-private/library', u'/Users/tgrimonet/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tgrimonet/Projects/ansible-devel/github/titom73/ansible-cvp-old-private/.venv/lib/python2.7/site-packages/ansible
  executable location = /Users/tgrimonet/Projects/ansible-devel/github/titom73/ansible-cvp-old-private/.venv/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```
