### ISSUE TITLE
cv_container - module fails if topology is empty

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#14]
If to make a container's clearnup, we provide an empty topology structure, module fails with following error message:

```shell
line 227, in create_new_containers\nTypeError: 'NoneType' object is not iterable
```

__Example playbook:__

```yaml
---
- name: Build Topology.
  hosts: cvp
  connection: local
  gather_facts: no
  vars:
    verbose: False
    containers_cleanup:
  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      cv_facts:
        host: '{{ansible_host}}'
        username: '{{cvp_username}}'
        password: '{{cvp_password}}'
        protocol: https
      register: cvp_facts
      tags:
        - always

    - name: "Build Container topology on {{inventory_hostname}}"
      tags:
        - cleanup
      cv_container:
        host: '{{ansible_host}}'
        username: '{{cvp_username}}'
        password: '{{cvp_password}}'
        topology: '{{containers_cleanup}}'
        cvp_facts: '{{cvp_facts.ansible_facts}}'
```
