### ISSUE TITLE
When 2 configlets has similar name, cv_device does not bind the second configlet.

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#164]
## Issue Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Summary

When `cv_device` must attach 2 condiglet with similar name, only first configlet is taken. Second one is ignored.

## Role or Module Name

__Module name:__ `cv_device`
__`arista.cvp` version:__ `1.0.5`

`arista.cvp` collection and Python libraries version

```shell
# Ansible version
$ ansible --version
ansible 2.9.5
  config file = ~/lab-testing-emea/ansible.cfg
  configured module search path = ['~/lab-testing-emea/ansible-avd/library']
  ansible python module location = ~/.venv/arista-ansible/lib/python3.7/site-packages/ansible
  executable location = ~/.venv/arista-ansible/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:26) [Clang 11.0.0 (clang-1100.0.33.16)]
```

## Steps to reproduce

```yaml
---
CVP_DEVICES:
  DC1-L2LEAF1A:
    name: DC1-L2LEAF1A
    parentContainerName: DC1_L2LEAF1
    configlets:
      - GLOBAL-ALIASES
      - GLOBAL-ALAIASES2
      - RADIUS_LAB
      - DC1-AVD_DC1-L2LEAF1A
```

Issue is located in [this block](https://github.com/aristanetworks/ansible-cvp/blob/e3a3698e098c35f916a0f7df3a88388f6a46c25e/ansible_collections/arista/cvp/plugins/modules/cv_device.py#L304) for version `releases/v1.0.x`

```python
if add_configlet == configlet['name']:
    MODULE_LOGGER.debug(
        '%s == %s -> added to add_configlets', str(add_configlet), str(configlet['name']))
    add_configlets.append({'name': add_configlet, 'key': configlet['key']})
else:
    MODULE_LOGGER.debug(
        '%s != %s -> ignored', str(add_configlet), str(configlet['name']))
```

Error message is:

```
arista.cvp.cv_device: DEBUG - func: device_action (L:368) - configlet from facts is GLOBAL-ALIASES2
arista.cvp.cv_device: DEBUG - func: device_action (L:375) - GLOBAL-ALAIASES2 != GLOBAL-ALIASES2 -> ignored
```

### Expected results

Devices should have all 4 configlets attached.

### Actual results

`GLOBAL-ALIASES2` is ignored by `cv_configlet`
