### ISSUE TITLE
State:absent is not working in cv_configlet module

### ISSUE THREAD

**Issue by mahmutaydin1** [aristanetworks/ansible-cvp#169]
## Summary
I am using cv_configlet module. When state : absent, configlet is not deleted on CVP.
Also, I can not update  inside of existing configlet.
Could you please help me?

## Role or Module Name
__Module name:__ `cv_configlet`

## Steps to reproduce

- name: Build First CVP Configlet
  hosts: cvp
  connection: local
  gather_facts: no
  collections:
    - arista.cvp

  vars:
    configlet_list:
      Test_Configlet1: "interface management1\n description Mahmut"

  tasks:
    - name: 'Collecting facts from CVP {{inventory_hostname}}.'
      arista.cvp.cv_facts:
      register: cvp_facts

    - name: 'Create configlets on CVP {{inventory_hostname}}.'
      arista.cvp.cv_configlet:
        cvp_facts: "{{cvp_facts.ansible_facts}}"
        configlets: "{{configlet_list}}"
        state: absent

### Expected results

Deletion of configlet on CVP, but not

**Comment by titom73** [comment]
Dear @mahmutaydin1 

To support deletion you have to configure `configlet_filter` as stated in [this documentation](https://github.com/aristanetworks/ansible-cvp/wiki/Modules-Documentation#manage-configlets-in-cloudvision).

The reason behind that is to protect deletion process and reduce risk to remove too many configlets as expected.

Below is an example with `configlet_filter` configured:

```yaml
---
- name: Build Switch configuration
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    CONFGILGET_TO_REMOVE:
      GLOBAL-ALIASES: "{{lookup('file', 'configlets/GLOBAL-ALIASES.conf')}}"
      GLOBAL-ALIASES2: "{{lookup('file', 'configlets/GLOBAL-ALIASES2.conf')}}"
  tasks:
    - name: "collect CV facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
        facts:
          configlets
      register: CVP_FACTS
    - name: 'delete configlets from cloudvision {{inventory_hostname}}'
      arista.cvp.cv_configlet:
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        configlets: "{{CONFGILGET_TO_REMOVE}}"
        configlet_filter: ["GLOBAL"]
        state: absent
      register: result

    - debug:
        msg: '{{result}}'
```

And playbook result shows correct deletion of my 2 configlets:

```shell
ansible-playbook dc1-remove-configlets.yml

PLAY [Build Switch configuration] ****************

TASK [collect CV facts cv_server] ****************
ok: [cv_server]

TASK [delete configlets from cloudvision cv_server] ****************
changed: [cv_server]

TASK [debug] ****************
ok: [cv_server] =>
  msg:
    changed: true
    data:
      deleted:
      - GLOBAL-ALIASES: success
      - GLOBAL-ALIASES2: success
      new: []
      tasks: []
      updated: []
    failed: false

PLAY RECAP ****************
cv_server                  : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
