### ISSUE TITLE
Deleting one container in a nested container does not work

### ISSUE THREAD

**Issue by noredistribution** [aristanetworks/ansible-cvp#173]
Currently it seems like removing a single container only works if the container's parent is the root (by default called Tenant ) container; if the container's parent is a child container of the root container, the playbook gets stuck 

e.g.

Non-working vars example

```
  vars:
      run_tasks: false
      run_mode: delete
      container_delete:
         DC1-Leaf-A:
             parent_container: DC1-Leafs
```

Working vars example1:

```
  vars:
      run_tasks: false
      run_mode: delete
      container_delete:
         DC1:
             parent_container: Tenant
```

Working vars example2:

```
  vars:
      run_tasks: false
      run_mode: delete
      container_delete:
         DC1:
             parent_container: Tenant
         DC1-Leafs:
             parent_container: Ankara
         DC1-Leaf-A:
             parent_container: DC1-Leafs
         DC1-Leaf-B:
             parent_container: DC1-Leafs
```
