### ISSUE TITLE
cv_container crash when trying to attach first configlet

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#190]
## Issue Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Summary

In version `1.1.0`, when `cv_container` module try to attach a configlet to a container with no container already configured, module fails with following error message

```
cv_container.py\", 
line 922, in configure_configlet_to_container\n
TypeError: 'NoneType' object is not subscriptable\n
```

## Role or Module Name

__Module name:__ `cv_container`

`arista.cvp` collection and Python libraries version

```shell
# Ansible version
$ ansible --version
2.9.6
```

## OS / Environment

__Cloudvision version__

`2019.1.3`

__EOS Version__

N/A

__OS running Ansible__

`Centos`

## Steps to reproduce

__Playbook__

```yaml
---
- name: lab04 - cv_container lab
  hosts: CloudVision
  connection: local
  gather_facts: no

  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
      register: CVP_FACTS

    - name: "Configure configlet on {{inventory_hostname}}"
      arista.cvp.cv_configlet:
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        configlets: "{{CVP_CONFIGLETS}}"
        configlet_filter: ["TRAINING"]
        state: present
      register: CVP_CONFIGLET_RESULT

    - name: "Configure containers on {{inventory_hostname}}"
      arista.cvp.cv_container:
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        topology: "{{CVP_CONTAINERS}}"
        mode: merge
      register: CVP_CONTAINERS_RESULT

    - name: 'Display cv_configlet result'
      debug:
        msg: '{{CVP_CONTAINERS_RESULT}}'

```

__Variables__

```yaml
---
CVP_CONFIGLETS:
  01TRAINING-alias: "alias a{{ 999 | random }} show version"
  01TRAINING-01: "alias a{{ 999 | random }} show version"

CVP_CONTAINERS:
  TRAINING:
    parent_container: Tenant
  TRAINING_DC:
    parent_container: TRAINING
  TRAINING_LEAFS:
    parent_container: TRAINING_DC
  TRAINING_SPINES:
    parent_container: TRAINING_DC
    configlets:
      - '01TRAINING-01'
    devices:
      - 'spine1'

```

### Expected results

```shell
$ ansible-playbook test-playbook.yml
PLAY RECAP  ****
CloudVision                : ok=4    changed=1
```

### Actual results

```shell
$ ansible-playbook test-playbook.yml

cv_container.py\", 
line 922, in configure_configlet_to_container\n
TypeError: 'NoneType' object is not subscriptable\n
```
