### ISSUE TITLE
cv_configlet - module fails if list of configlet is empty

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#21]
Should support an empty list for CVP cleanup like for `cv_container` with Issue #14 

```yaml
---
- name: Test cv_configlet_v2
  hosts: cvp
  connection: local
  gather_facts: no
  vars:
    configlets_delete:
  tasks:
    - name: 'Use Empty configlet list to deploy on CVP {{inventory_hostname}}.'
      tags:
        - cleanup
      cv_configlet:
        host: "{{ansible_host}}"
        username: '{{cvp_username}}'
        password: '{{cvp_password}}'
        protocol: https
        port: '{{cvp_port}}'
        cvp_facts: "{{cvp_facts.ansible_facts}}"
        configlets: "{{configlets_delete}}"
        # cvp_filter: ["Test","base-chk","base-firewall"]
      register: cvp_configlet
```
