### ISSUE TITLE
cv_container - Update module for Grant

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#23]
Align `cv_container` with new information provided by `cv_facts` module.

It also has to use following input structure:

```yaml
---
container_topology: 
   Fabric:
      parent_container: Tenant
   Spines:
      parent_container: Fabric
      configlets:
        - container_configlet
      images:
        - 4.22.0F
      devices:
        - veos01
```

__Module features:__

- [x] Container creation / deletion for `2018.2.x`
- [x] Container creation / deletion for `2019.1.x`
- [x] Device move to the correct container  for `2018.2.x`
- [x] Device move to the correct container  for `2019.1.x`
- [x] Configlet attachement (previously created by `cv_configlet`)  for `2018.2.x`
- [x] Configlet attachement (previously created by `cv_configlet`)  for `2019.1.x`
- [x] Module output definition: list of actions & `taskIds`

**Comment by titom73** [comment]
__Task done:__

- Update key used by `cv_facts`
- Same functionality as previous version: intend approach to add/delete/update
- Support CVP version 2018.2.x only
- No requirements from cvprac.

__Todo:__

- Create back-end for Grant
- Update input management to align with model provided in issue.

**Comment by titom73** [comment]
__Features supported__

- Add container(s) described in topology
- Delete unused container(s)
- Auto ignore containers with devices or with children

__Supported Version:__

- 2018.2.x

__Test topology:__

```yaml
vars:
    verbose: False
    containers_cleanup:
    containers_build:
        Fabric:
            parent_container: Tenant
        Spines:
            parent_container: Fabric
            configlets:
                - container_configlet
        Leaves:
            parent_container: Fabric
            configlets:
                - container_configlet
```

__Build run__

```shell
ansible-playbook playbook.container.demo.yaml --limit cvp_foster --tags build

PLAY [Playbook to validate and demonstrate cv_container module.] ***

TASK [Gather CVP facts from cvp_foster] ***
Saturday 12 October 2019  15:36:02 +0200 (0:00:00.032)       0:00:00.032 ******
ok: [cvp_foster]

TASK [Build Container topology on cvp_foster] ***
Saturday 12 October 2019  15:36:15 +0200 (0:00:13.564)       0:00:13.597 ******
changed: [cvp_foster]

TASK [Check if Leaves container exists] ***
Saturday 12 October 2019  15:36:23 +0200 (0:00:07.920)       0:00:21.517 ******
ok: [cvp_foster]

TASK [Check if Leaves container exists] ***
Saturday 12 October 2019  15:36:37 +0200 (0:00:13.584)       0:00:35.102 ******
ok: [cvp_foster] => {
    "changed": false,
    "msg": "Leaves container has been found as expected"
}

PLAY RECAP ***
cvp_foster                 : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Saturday 12 October 2019  15:36:37 +0200 (0:00:00.024)       0:00:35.126 ***
===============================================================================
Check if Leaves container exists --------------------------------------------------------------------------------------------- 13.58s
Gather CVP facts from cvp_foster --------------------------------------------------------------------------------------------- 13.56s
Build Container topology on cvp_foster ---------------------------------------------------------------------------------------- 7.92s
Check if Leaves container exists ---------------------------------------------------------------------------------------------- 0.02s
```

__Cleanup run__

```shell
ansible-playbook playbook.container.demo.yaml --limit cvp_foster --tags cleanup

PLAY [Playbook to validate and demonstrate cv_container module.] ***

TASK [Gather CVP facts from cvp_foster] ***
Saturday 12 October 2019  15:36:42 +0200 (0:00:00.035)       0:00:00.035 ******
ok: [cvp_foster]

TASK [Cleanup Container topology on cvp_foster] ***
Saturday 12 October 2019  15:36:58 +0200 (0:00:15.352)       0:00:15.388 ******
changed: [cvp_foster]

TASK [Gather CVP facts from cvp_foster] ***
Saturday 12 October 2019  15:37:07 +0200 (0:00:08.902)       0:00:24.290 ******
ok: [cvp_foster]

TASK [Check if Leaves container has been removed] ***
Saturday 12 October 2019  15:37:19 +0200 (0:00:12.888)       0:00:37.178 ******
ok: [cvp_foster] => {
    "changed": false,
    "msg": "Leaves container has not been found as expected"
}

PLAY RECAP ***
cvp_foster                 : ok=4    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

Saturday 12 October 2019  15:37:19 +0200 (0:00:00.023)       0:00:37.201 ***
===============================================================================
Gather CVP facts from cvp_foster --------------------------------------------------------------------------------------------- 15.35s
Gather CVP facts from cvp_foster --------------------------------------------------------------------------------------------- 12.89s
Cleanup Container topology on cvp_foster -------------------------------------------------------------------------------------- 8.90s
Check if Leaves container has been removed ------------------------------------------------------------------------------------ 0.02s
```
