### ISSUE TITLE
cv_device - Update to be idempotent

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#24]
Data structure to use as module inputs:

```yaml
---
 devices_list:
     veos1
     veos02:
        configlets:
          - Test_Configlet
        images:
          - 4.22.1F
```
