### ISSUE TITLE
cv_configlet with state set to absent adds configlets to CVP

### ISSUE THREAD

**Issue by aphillipps** [aristanetworks/ansible-cvp#258]
## Summary

When state it set to absent in a playbook to delete configlets in CVP using cv_configlet module, if the configlets listed to delete have already been deleted in CVP, the playbook adds them again to CVP.

## Role or Module Name

__Module name:__ `cv_configlet`

### Playbook used for the test:

```yaml
---
- name: lab04 - cv_configlet lab
  hosts: CloudVision
  connection: local
  gather_facts: no

  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
        facts:
          configlets
      register: CVP_FACTS

    - name: "Configure configlet on {{inventory_hostname}}"
      arista.cvp.cv_configlet:
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        configlets: "{{CVP_CONFIGLETS}}"
        configlet_filter: ["TRAINING"]
        state: absent
      register: CVP_CONFIGLET_RESULT
```
