### ISSUE TITLE
Add explicit delete option via absent=True

### ISSUE THREAD

**Issue by networkop** [aristanetworks/ansible-cvp#27]
With the new idempotent approach the only way to delete an object is by removing a reference to it. This works fine for some cases, but sometimes it may be required to explicitly remove large number of objects (e.g. cleanup, migration) or undo the previously created state. A lot of Ansible's core modules support  an optional `state` parameter, which can be passed to tasks and modules to explicitly modify state.

I think, once we get the idempotent behaviour sorted for all our main resources, we can add this fairly easily.
For Example :
```
    - name: 'Create configlets on CVP {{inventory_hostname}}.'
      cv_configlet:
        configlets: "{{configlet_list}}"
        configlet_filter: ["New", "Test","base-chk","base-firewall"]
      state: absent
````
Will delete all configlets from "{{configlet_list}}" from CVP.
