### ISSUE TITLE
The use of lookup('file', '...) for configlets fails input validation

### ISSUE THREAD

**Issue by kjellrg** [aristanetworks/ansible-cvp#313]
## Issue Type

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation Report
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Other (please describe):

## Summary

The use of lookup('file', 'path') for configlets fails after input validation with JSON schema was added.

e.g.:
      LEAF-DEFAULT: "{{ lookup('file', '../arista/configs/LEAF-DEFAULT.txt') }}"

cv_configlet tasks fails with:
fatal: [server01]: FAILED! => {"changed": false, "msg": "Configlet input data are not compliant with module."}

## Role or Module Name

__Module name:__ `module name`

`arista.cvp` collection and Python libraries version

```shell
# Ansible version
ansible 2.9.19

# ansible-cvp version
v2.1.1
```

## OS / Environment

__Cloudvision version__

2020.3.1

__EOS Version__

4.25.2F

__OS running Ansible__

Ubuntu

## Steps to reproduce

Have a configlet in configlet_list use the lookup() function

      LEAF-DEFAULT: "{{ lookup('file', '../arista/configs/LEAF-DEFAULT.txt') }}"

```yaml
---
```

### Expected results

Have the cv_configlet task complete and update the configlets on CVP if there are any changes to the file specified.

```shell
$
```

### Actual results

cv_configlet tasks fails with:
fatal: [server01]: FAILED! => {"changed": false, "msg": "Configlet input data are not compliant with module."}

Edit the file: ansible-cvp/ansible_collections/arista/cvp/plugins/module_utils/schema.py
and changing patternProperties under SCHEMA_CV_CONFIGLET to ".*" makes the configlets pass validation and work as before. Not sure what proper regex to use to allow for the lookup() function.

```shell
$
```

**Comment by titom73** [comment]
Hello @kjellrg 

As per this error message, it seems var structure for your configlet is not valid.

I have run the following playbook successfully. Can you test with your own setup ?

```yaml
---
- name: Upload configlet
  hosts: cv_server
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    CVP_CONFIGLETS:
      01DEMO-alias: "alias a{{ 999 | random }} show version"
      01DEMO-01: "alias a{{ 999 | random }} show version"
      01DEMO-02: "alias sib show interface brief"
      01DEMO-03: "{{lookup('file', '../configlets/DEVICE-ALIASES.conf')}}"

  tasks:
    - name: "Gather CVP facts {{inventory_hostname}}"
      arista.cvp.cv_facts:
        facts:
          configlets
      register: CVP_FACTS

    - name: "Configure configlet on {{inventory_hostname}}"
      arista.cvp.cv_configlet:
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        configlets: "{{CVP_CONFIGLETS}}"
        configlet_filter: ["DEMO"]
        state: present
      register: CVP_CONFIGLET_RESULT
```

> Note that lookup is done based on `playbook_dir`
