### ISSUE TITLE
Configlets not removed from container with cv_container_v3 in strict mode

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#347]
## Issue Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation Report
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes)
- [ ] Other (please describe):

## Summary

When `cv_device_v3` is used in `strict` mode and `configlets` list is removed from container, configlets are not removed on CV side.

## Role or Module Name

`arista.cvp.cv_container_v3`

**Comment by titom73** [comment]
Following dataset works:

```yaml
CVP_CONTAINERS_V3:
      DC2:
        parentContainerName: Tenant
      Spines_DC2:
        parentContainerName: DC2
        configlets: []
          # - 'ASE_DEVICE-ALIASES'
          # - '01DEMO-01'
          # - '01DEMO-02'
```

But this one does not work:

```yaml
CVP_CONTAINERS_V3:
      DC2:
        parentContainerName: Tenant
      Leafs_DC2:
        parentContainerName: DC2
      Spines_DC2:
        parentContainerName: DC2
```
