### ISSUE TITLE
Feature Request - Add support for absent/factory-reset in cv_device_v3 module

### ISSUE THREAD

**Issue by guillaumeVilar** [aristanetworks/ansible-cvp#361]
## Request Type

- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Other (please describe):

## Detailed Description
In the current version (3.0), we do not support the absent mode for the state field (only present is supported): 

```
  tasks:
    - name: "Absent device"
      arista.cvp.cv_device_v3:
        devices: "{{devices}}"
        state: absent
```
Result: 
```
TASK [Absent device] ***********************************************************************************************************************************************************************************************************************
Monday 24 May 2021  11:34:30 +0100 (0:00:00.033)       0:00:00.033 ************ 
Monday 24 May 2021  11:34:30 +0100 (0:00:00.032)       0:00:00.032 ************ 
fatal: [cv_server]: FAILED! => changed=false 
  msg: State==absent is not yet supported !

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
cv_server                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

## Context
Should give the ability to remove devices in 2 different ways: 
* Remove the device from the provisioning page (same action as in the UI: right-click on device > Remove).
Trial syntax : 
```
    - name: "Absent device"
      arista.cvp.cv_device_v3:
        devices: "{{devices}}"
        state: absent
```

* Factory reset the device (in the UI: right-click on device > Factory Reset)
Trial syntax: 
```
    - name: "Factory reset device"
      arista.cvp.cv_device_v3:
        devices: "{{devices}}"
        state: factory_reset
```
