### ISSUE TITLE
arista.cvp.cv_container_v3 reports change even when there is no change

### ISSUE THREAD

**Issue by dgethings** [aristanetworks/ansible-cvp#427]
### Issue Summary

Hi,

With the following task `status.changed` always returns `True` even when no change it made.

```yaml
    - name: create containers on CVP
      arista.cvp.cv_container_v3:
        topology: "{{ topology }}"
        state: present
        apply_mode: loose
      register: status

    - debug:
        var: status
```

Here is the output from the task and debug 

```bash
TASK [create containers on CVP] ***************************************************************************************************************************************************************
changed: [cv_server]

TASK [debug] **********************************************************************************************************************************************************************************
ok: [cv_server] => {
    "status": {
        "changed": true,
        "configlets_attached": {
            "changed": true,
            "configlets_attached_count": 0,
            "configlets_attached_list": [
                "Global:",
                "site2:",
                "s2-leaves:"
            ],
            "diff": {},
            "success": true,
            "taskIds": []
        },
        "configlets_detached": {
            "changed": false,
            "configlets_detached_count": 0,
            "configlets_detached_list": [],
            "diff": {},
            "success": true,
            "taskIds": []
        },
        "container_added": {
            "changed": false,
            "container_added_count": 0,
            "container_added_list": [],
            "diff": {},
            "success": false,
            "taskIds": []
        },
        "container_deleted": {
            "changed": false,
            "container_deleted_count": 0,
            "container_deleted_list": [],
            "diff": {},
            "success": false,
            "taskIds": []
        },
        "failed": false,
        "success": true,
        "taskIds": []
    }
}
```

### Which component(s) of AVD impacted

cv_container_v3

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Input variables

```yaml
topology:
      Global:
        parentContainerName: Tenant
      site2:
        parentContainerName: Global
      s2-leaves:
        parentContainerName: site2
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
