### ISSUE TITLE
removing all configlets from a container doesn't work

### ISSUE THREAD

**Issue by noredistribution** [aristanetworks/ansible-cvp#443]
### Issue Summary

When trying to unassign/detach all configlets from a container (`apply_mode: strict) currently it seems the behavior is to only try to unassign configlet if there's at least one configlet specified in the vars in ansible, so there'll be always at least 1 configlet that will not be unassigned, so no configlets will be touched with the current implementation if the configlets list is empty for a container in the vars

simply adding a condition to also check for strict mode if there are no configlets specified in the vars and unassign all the configlets fixes this since we never enter this condition https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/module_utils/container_tools.py#L821 so we never get to https://github.com/aristanetworks/ansible-cvp/blob/devel/ansible_collections/arista/cvp/plugins/module_utils/container_tools.py#L825, but in the case where we want to remove all configlets basically `configlet_to_remove` should be `attached_configlets`

### Which component(s) of AVD impacted

cv_container_v3

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Input variables

```yaml
---
- name: lab05 - cv_container_v3 lab
  hosts: CloudVision
  connection: local
  gather_facts: no
  vars:
    CVP_CONFIGLETS:
      01TRAINING-alias: "alias srnz show interfaces counters rates | nz"
      01TRAINING-01: "alias a{{ 999 | random }} show version"

    CVP_CONTAINERS:
      Tenant:
         parentContainerName: Tenant
  tasks:
    - name: "Configure containers on {{inventory_hostname}}"
      arista.cvp.cv_container_v3:
        topology: "{{CVP_CONTAINERS}}"
        state: present
        apply_mode: strict
      register: CVP_CONTAINERS_RESULT
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
