### ISSUE TITLE
Fix search_key option in cv_device_v3 module

### ISSUE THREAD

**Issue by tstarck** [aristanetworks/ansible-cvp#456]
### Issue Summary

Unable to use cv_device_v3 module successfully with any argument except `search_key: fqdn`.

### Environment

Python 3.8.10
Ansible 2.12.2
ansible-cvp 3.2.0
cvprac 1.0.7
CVP cvaas

### Which component(s) of AVD impacted

cv_device_v3

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Input variables

Ansible task:

```yaml
- name: Attach configlets to devices
  arista.cvp.cv_device_v3:
    search_key: serialNumber
    devices: "{{ payload  }}"
```

Payload:

```json
{
  "configlets": [
    "__configletname"
  ],
  "parentContainerName": "Tenant",
  "serialNumber": "2468...ABCD"
}
```

### Steps to reproduce

1. Use cv_device_v3 module with `search_key: serialNumber`

### Relevant log output

From Ansible's module_stderr:

```
Traceback (most recent call last):
[...]
  File "/tmp/ansible_arista.cvp.cv_device_v3_payload_qkenv65p/ansible_arista.cvp.cv_device_v3_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device_v3.py", line 222, in <module>
  File "/tmp/ansible_arista.cvp.cv_device_v3_payload_qkenv65p/ansible_arista.cvp.cv_device_v3_payload.zip/ansible_collections/arista/cvp/plugins/modules/cv_device_v3.py", line 213, in main
  File "/tmp/ansible_arista.cvp.cv_device_v3_payload_qkenv65p/ansible_arista.cvp.cv_device_v3_payload.zip/ansible_collections/arista/cvp/plugins/module_utils/device_tools.py", line 790, in manager
  File "/tmp/ansible_arista.cvp.cv_device_v3_payload_qkenv65p/ansible_arista.cvp.cv_device_v3_payload.zip/ansible_collections/arista/cvp/plugins/module_utils/device_tools.py", line 1106, in deploy_device
  File "/root/.local/lib/python3.8/site-packages/cvprac/cvp_api.py", line 2827, in deploy_device
    self.move_device_to_container(app_name, device, container_info,
  File "/root/.local/lib/python3.8/site-packages/cvprac/cvp_api.py", line 1842, in move_device_to_container
    info = 'Device Add {} to container {} by {}'.format(device['fqdn'],
KeyError: 'fqdn'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tstarck** [comment]
I did some debugging trying to be helpful. Looking at device_tools.py method `deploy_device()`, it tries to:

```python
device_info = self.get_device_facts(device_lookup=device.fqdn)
```

That method does not find a device matching the search (when not `search_key: fqdn`) and always returns with an empty set. That empty set is then used when *cvprac* is called, which in turn fails because there's no `fqdn` key in dataset.

I patched the file with:

```diff
diff -u cvp/plugins/module_utils/device_tools.py cvp/plugins/module_utils/device_tools.py
index 2f0abdc..d067a04 100644
--- cvp/plugins/module_utils/device_tools.py
+++ cvp/plugins/module_utils/device_tools.py
@@ -1077,7 +1077,10 @@ class CvDeviceTools(object):
                     device_mac=device.system_mac)
                 MODULE_LOGGER.debug('Device {} is currently under {}'.format(
                     device.fqdn, *current_container_info['name']))
-                device_info = self.get_device_facts(device_lookup=device.fqdn)
+                if self.__search_by == FIELD_SERIAL:
+                    device_info = self.get_device_facts(device_lookup=device.serial_number)
+                else:
+                    device_info = self.get_device_facts(device_lookup=device.fqdn)
                 if (current_container_info['name'] == 'Undefined'):
                     if self.__check_mode:
                         result_data.changed = True
```

And it started working correctly for our use case.

But please note the patch above is only provided as a conversation piece and not a straight fix, because (1) it does not consider all use cases, (2) does not necessarily address the root cause, and (3) current `devel` branch has already moved forward.

**Comment by titom73** [comment]
Hello @tstarck 

We have tried to reproduce issue with latest version of the code and it is already fixed in the code. You can find below a playbook we used to reproduce your behaviour:

```yaml
- name: Cloudvision v3 test playbook
  hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp
  vars:
    execute_tasks: false
    CVP_DEVICES:
      - fqdn: leaf-1-unit-test
        hostname: leaf-1-unit-test
        serialNumber: A2BC88...251999
        parentContainerName: 'ansible-tests'
        configlets:
            - 'cvaas-unit-test-01'
            - 'leaf-1-unit-test'
            - leaf-2-unit-test
            - test_configlet
            - test_device_configlet
  tasks:
    - name: 'Display initial information'
      debug:
        msg: 'Connecting to {{ansible_host}} using token {{ansible_ssh_pass}}'

    - name: "Configure devices on {{inventory_hostname}}"
      arista.cvp.cv_device_v3:
        devices: "{{CVP_DEVICES}}"
        state: present
        search_key: serialNumber
      register: CVP_DEVICES_RESULTS

    - name: 'Display debug'
      debug:
        msg: '{{CVP_DEVICES_RESULTS}}'
```

As we are close to release a new version in the next couple of days, it would be great if you can confirm that the devel branch is working as fine before we issue this new release.

Please let us know if you need assistance in testing.

Regards,
