### ISSUE TITLE
feat(cv_facts_v3): add ipAddress to device facts

### ISSUE THREAD

**Issue by noredistribution** [aristanetworks/ansible-cvp#468]
### Enhancement summary

Seems like we're not outputting the `ipAddress` from the `get_inventory()` call

### Which component of AVD is impacted

other

### Use case example

wanted to generate inventory file from an on-prem instance but IP addresses are missing

so now when running facts
instead of 

```yaml
  - configlets:
    - vlangen
    - tp-avd_tp-avd-leaf2
    - vlan144
    fqdn: tp-avd-leaf2
    hostname: tp-avd-leaf2
    parentContainerName: TP_LEAF1
    serialNumber: 0123F2E4462997EB155B7C50EC148767
    systemMacAddress: 50:08:00:b1:5b:0b
```

I'm getting:

```yaml
  - configlets:
    - vlangen
    - tp-avd_tp-avd-leaf2
    - vlan144
    fqdn: tp-avd-leaf2
    hostname: tp-avd-leaf2
    ipAddress: 10.83.13.215
    parentContainerName: TP_LEAF1
    serialNumber: 0123F2E4462997EB155B7C50EC148767
    systemMacAddress: 50:08:00:b1:5b:0b
```

### Describe the solution you'd like

adding necessary functions to not filter out the mgmt ip of the devices

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
