### ISSUE TITLE
Error - the following devices do not exist in CVP | hostname contains a period

### ISSUE THREAD

**Issue by AristaJon** [aristanetworks/ansible-cvp#476]
### Issue Summary

"Error - the following devices do not exist in CVP ['dc-hw.spine1.lab.local'"

Issue is seen when the hostname contains a '.' in the name.

Workaround is to use search_key in the task to query on the fqdn vs. the hostname.

- name: "Assign devices to containers"
     arista.cvp.cv_device_v3:
      devices: "{{CVP_DEVICES}}"
      state: present
      search_key: fqdn

### Which component(s) of AVD impacted

cv_device

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Input variables

```yaml
CVP_DEVICES:
    - fqdn: 'dc-hw.spine1.lab.local'
      parentContainerName: 'h_Spines'

 tasks:

   - name: "Assign devices to containers"
     arista.cvp.cv_device_v3:
      devices: "{{CVP_DEVICES}}"
      state: present
     register: CVP_DEVICES_DEFAULT
```

### Steps to reproduce

```shell
use a device hostname with a period '.'  in the name.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
