### ISSUE TITLE
Feat: (dhcp_configuration)  add a name to the dhcp record

### ISSUE THREAD

**Issue by pvinci-arista** [aristanetworks/ansible-cvp#480]
### Enhancement summary

If you are configuring more than one subnet, add a name for reference and render it as a comment in the config file.

### Which component of AVD is impacted

other

### Use case example

multiple ztp subnets.

### Describe the solution you'd like

Add a new key:

```yaml
ztp:
  general:
    subnets:
     - name: DC2 OOB network
       network: 10.0.0.0
       netmask: 255.255.255.0
     - ...
```

which would render as : 
```
# DC2 OOB network
subnet 10.0.0.0 netmask 255.555.555.0 {
...
}
```

### Describe alternatives you've considered

None.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
