### ISSUE TITLE
Feat(cv_tag_v3): Add Auto-delete option to cv_tag_v3

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-cvp#501]
### Enhancement summary

Add `auto_delete` option to `cv_tag_v3`. When `auto_delete=True` and `mode=unassign`, tags are unassigned from the device and deleted

### Which component of AVD is impacted

other

### Use case example

```
- name: Test cv_tag_v3
  hosts: CloudVision
  connection: local
  gather_facts: no
  vars:
    CVP_TAGS:
      - device: leaf1
        device_tags:
          - name: tag1
            value: value1
          - name: tag2
            value: value2
  tasks:
    - name: create tags
      arista.cvp.cv_tag_v3:
        tags: "{{CVP_TAGS}}"
        mode: unassign
        auto_delete: true
```
This will unassign `tag1` and `tag2` from `leaf1` and delete them from the CVP

### Describe the solution you'd like

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
