### ISSUE TITLE
cv_change_control_v3: Add support for approve/execute actions

### ISSUE THREAD

**Issue by pmerlo2022** [aristanetworks/ansible-cvp#526]
### Enhancement summary

Add the following capabilities to cv_change_control_v3:
- approve a change control given a change control id or name
- execute a change control given a change control id or name

Ideally the enhancement also provides the ability to both approve and execute a change control within a single task.

### Which component of AVD is impacted

cv_change_control_v3

### Use case example

The cv_change_control_v3 role already provides the capability to create, remove and show change controls This request is to add approve/execute choices following the existing design.

### Describe the solution you'd like

The solution should add new state choices: < approve | execute | approve_and_execute >

Example 1:
```
    - name: "Approve Change Control"
       arista.cvp.cv_change_control_v3:
        state: approve
        name: change.name
    - name: "Execute Change Control"
       arista.cvp.cv_change_control_v3:
        state: execute
        name: change.name
```

Example 2:
```
    - name: "Approve and Execute Change Control"
       arista.cvp.cv_change_control_v3:
        state: approve_and_execute
        name: another_change.name
```

Other considerations:
- Executing an unapproved change control must result in a failure
- Scenario where same user that creates the change control approves it - this should result in a failure

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
