### ISSUE TITLE
Feat: expose `verbose` option in cv_facts_v3

### ISSUE THREAD

**Issue by sugetha24** [aristanetworks/ansible-cvp#534]
### Enhancement summary

cv_facts_v3 has a `verbose` option that isn't exposed. 
This gets all facts on devices. 

### Which component of AVD is impacted

cv_facts_v3

### playbook
```
- name: "#01 - Collect devices facts from {{inventory_hostname}}"
      tags: [facts]
      arista.cvp.cv_facts_v3:
        facts:
          - devices
        regexp_filter: "tp-avd-spine1"
        verbose: long
```

### output:
```
ok: [CloudVision] => 
  msg:
  - architecture: ''
    bootupTimeStamp: 0
    bootupTimestamp: 0
    complianceCode: '0001'
    complianceIndication: WARNING
    containerName: TP_SPINES
    danzEnabled: false
    dcaKey: null
    deviceInfo: Registered
    deviceStatus: Registered
    deviceType: eos
    domainName: ''
    fqdn: tp-avd-spine1.tst
    hardwareRevision: ''
    hostname: tp-avd-spine1.tst
    internalBuild: ''
    internalBuildId: ''
    internalVersion: 4.28.2F
    ipAddress: 10.83.13.212
    isDANZEnabled: false
    isMLAGEnabled: false
    key: 50:08:00:8b:ee:b1
    lastSyncUp: 0
    memFree: 0
    memTotal: 0
    mlagEnabled: false
    modelName: vEOS-lab
    parentContainerId: container_d6e4aa41-07f0-45ee-bfeb-4b4c857771f5
    parentContainerKey: container_d6e4aa41-07f0-45ee-bfeb-4b4c857771f5
    parentContainerName: TP_SPINES
    serialNumber: CD0EADBEEA126915EA78E0FB4DC776CA
    sslConfigAvailable: false
    ```

### Describe the solution you'd like

expose `verbose` keyword to be set from the playbook in the module level

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
