### ISSUE TITLE
Implement mode for cv_container

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#58]
## Implement mode for `cv_container`

__CLI Implementation__

```yaml
  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      cv_facts:
      register: cvp_facts
    - name: "Build Container topology on {{inventory_hostname}}"
      cv_container:
        topology: '{{containers_provision}}'
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        mode: merge
        save_topology: true
```

__Supported keywords:__

	□ merge
	□ override
	□ delete
	

__Keywords description:__

- B(override) - Discard the entire existing container topology and replace it
with the new topology. If devices are attached to containers, these ones are not deleted.

- B(merge) - Combine the new container topology with the existing
topology. If containers in the new toplogy conflict with
containers in the existing toplogy, the containers definition in
the new topology replace those in the existing
Topology (mainly used for device attachement).

- B(delete) - Discard the entire container topology provided in B(topology) and keep other existing containers untouched.
