### ISSUE TITLE
Implement filter for cv_container

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#59]
## Implement filter option

__CLI Implementation__

```yaml
  tasks:
    - name: "Gather CVP facts from {{inventory_hostname}}"
      cv_facts:
      register: cvp_facts
    - name: "Build Container topology on {{inventory_hostname}}"
      cv_container:
        topology: '{{containers_provision}}'
        cvp_facts: '{{cvp_facts.ansible_facts}}'
        filter: ['DC1', 'DC2']
        save_topology: true
```

__Supported keywords:__

	□ List of string to match
	

__Keywords description:__

- If B(filter) is set, then, cv_container will only manage containers started with any of these prefixes or attached to a container using these prefixes.
- If B(filter) is unset, behavior will be applied to all containers on CVP and within expected topology
