### ISSUE TITLE
Multiple device Configlets not correctly validated when they depend on each other

### ISSUE THREAD

**Issue by gusmb** [aristanetworks/ansible-cvp#665]
### Issue Summary

`cv_validate_v3` does not validate configlets for a device as ONE config, but each configlet individually. This causes false positives when a configlet contains dependencies to other configlets that are applied to the device before in the list.

### Which component(s) of AVD impacted

other

### How do you run AVD ?

Ansible CLI (with virtual-env or native python)

### Input variables

```yaml
---
CVP_DEVICES:
  - device_name: XXXXXXXXX
    search_type: serialNumber
    local_configlets:
      device1.cfg: "main configlet contents omitted"
      device1-extra.cfg: “custom configlet contents omitted"

  - device_name: YYYYYYYYY
    search_type: serialNumber
    local_configlets:
      device2.cfg: "main configlet contents omitted"
      device2-extra.cfg: “custom configlet contents omitted"
```

### Steps to reproduce

```shell
1. Create a device configlet that configures a VRF instance
2. Create a second configlet that configures a static route on that VRF
3. Apply both configlets on CVP for that device in the right order
4. Run `cv_validate_v3` role with the vars above. It will fail validation for the "extra" config, reporting that the VRF instance does not exist.

I would expect the validation of config to be done per-device, not per-configlet, applying all relevant device-level configlets in the right order, as it would be done when validating the config on CVP. Otherwise, the role is just limited to test a valid configlet that contains configuration which don't have any dependencies on other configlets.
```

### Relevant log output

```shell
fatal: [cvp1]: FAILED! => changed=false
  msg:
  - configlet_name: device1-extra.cfg
    device: XXXXXXX
    errors:
    - error: '> ipv6 unicast-routing vrf TEST% No such VRF TEST. at line 8'
      lineNo: ' 8'
  - configlet_name: device2-extra.cfg
    device: YYYYYYY
    errors:
    - error: '> ipv6 unicast-routing vrf TEST% No such VRF TEST. at line 8'
      lineNo: ' 8'
```

vrf instance TEST was defined on `device1.cfg` and `device2.cfg` respectively

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
