### ISSUE TITLE
cv_configlet add multiple time task to list.

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#82]
Issue Type
------
 - Bug Report

Module Name
------

`cv_container`

Summary
------

Under certain circumstances, `cv_container` will append multiple times same taskIds to the list raising issue in `cv_task` when module tries to execute a task already completed.

Steps to reproduce
------

```yaml
---
- name: Playbook to validate and demonstrate cv_container module.
  hosts: cvp
  connection: local
  gather_facts: no
  vars:
    verbose: False
    configlet_list:
          ANSIBLE_TESTING_CONTAINER: "alias a{{ 999 | random }} show version"
          ANSIBLE_TESTING_VEOS: "alias a{{ 999 | random }} show version"
    device_provision:
      veos01:
        name: veos01
        configlets:
          - ANSIBLE_TESTING_VEOS
          - SYS_TelemetryBuilderV2_172.23.0.2_1
          - veos01-basic-configuration
          - SYS_TelemetryBuilderV2
      veos02:
        name: veos02
        configlets:
          - ANSIBLE_TESTING_VEOS
          - SYS_TelemetryBuilderV2_172.23.0.3_1
          - SYS_TelemetryBuilderV2
          - veos02-basic-configuration
      veos03:
        name: veos03
        parentContainerName: Spines
        configlets:
          - SYS_TelemetryBuilderV2_172.23.0.4_1
          - SYS_TelemetryBuilderV2
          - veos03-basic-configuration
    containers_provision:
        Fabric:
          parent_container: Tenant
        Spines:
          parent_container: Fabric
        Leaves:
          parent_container: Fabric
          configlets:
              - ANSIBLE_TESTING_CONTAINER
        MLAG01:
          parent_container: Leaves
          devices:
            - veos01
            - veos02

  tasks:
    - name: '#01 - Collect initial facts from {{inventory_hostname}}'
      cv_facts:
      register: FACTS
    
    - name: '#02 - Configure Configlets on {{inventory_hostname}}'
      cv_configlet:
        cvp_facts: "{{FACTS.ansible_facts}}"
        configlets: "{{configlet_list}}"
        configlet_filter: ["all"]
      register: CONFIGLETS

    - name: '#03 - Configure Container topology on {{inventory_hostname}}'
      cv_container:
        cvp_facts: "{{FACTS.ansible_facts}}"
        topology: '{{containers_provision}}'
        save_topology: true
      register: CONTAINERS

    - name: '#04 - Display Containers Information'
      debug:
        msg: "{{CONTAINERS}}"

    - name: '#05 - Execute pending tasks -- timeout 60sec'
      cv_task:
        tasks: "{{ CONTAINERS.cv_container.tasks }}"
        wait: 60
```

Expected results

All tasks generated by `cv_container` to be executed.

Actual results
------

```
"taskIds": [
    "244", 
    "245", 
    "244", 
    "245", 
    "246", 
    "246", 
    "244", 
    "245"
]
```
