### ISSUE TITLE
Feature Request - Support option to gather device config in cv_fact

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#89]
**Is your feature request related to a problem? Please describe.**

In large environment, collecting facts is getting more and more time because of collecting device configuration for every streaming device in CVP.

These configurations are not necessary in most of scenario as modules only focus on CVP provisionning and not on EOS device configuration.

As facts could be collected at different times in playbooks, overall execution time can be very important.

**Describe the solution you'd like**

An example of implementation might be:

```yaml
- name: collect default set of facts
  cv_fact:

- name: collect default set of facts and eos configuration
  cv_fact:
    gather_subset: config
```

With this approach it is easy to extend this option to any other additional content like lldp or any command output.
