### ISSUE TITLE
Feature Request - Allow cv_facts to only target a subgroup of facts

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#95]
**Is your feature request related to a problem? Please describe.**

In some scenario, it might be important to rerun `cv_facts` to refresh a list of objects.

Current implementation requires to update everything and it might be time consuming in large deployments.

**Describe the solution you'd like**

Like `gather_subset` implemented in PR #92 , an option to target only a subset of facts would be useful. An approach might be:

```yaml
  tasks:
    - name: '#01 - Collect devices facts from {{inventory_hostname}}'
      cv_facts_v2:
        facts:
          devices
      register: FACTS_DEVICES
```

In the meantime, it would be interesting to get access to fields sent by CVP as stated in issue #30 

**Describe alternatives you've considered**

Alternative could be to update modules to refresh facts on the fly when needed by module. This approach might lead to non-optimum behavior as every time, module may have to resolve dependencies and execute more API calls than `cv_facts` do.
