### ISSUE TITLE
Implement state=absent to reset devices in cv_device

### ISSUE THREAD

**Issue by titom73** [aristanetworks/ansible-cvp#99]
Like `cv_configlet`, it might be useful to get an option in `cv_device` to reset devices and move them back to undefined container.

__Playbook example__

```yaml
- name: Build Switch configuration
  hosts: DC1_FABRIC
  connection: local
  gather_facts: no
  vars:
      CVP_DEVICES:
        DC1-SPINE1:
          name: DC1-SPINE1
          parentContainerName: DC1_SPINES
          configlets:
              - AVD_DC1-SPINE1
          imageBundle: []
  tasks:
    - name: Get facts
      cv_facts
      register: FACTS
    - name: reset devices
      cv-device:
        devices: "{{CVP_DEVICES}}"
        cvp_facts: '{{FACTS.ansible_facts}}'
        device_filter: ['DC1']
        state: absent
```

__Expected results__

- Devices moves back to undefined.
- Clean configuration.
- Restart ZTP process to onboard device.
